#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

# Which carpentry is this ("swc", "dc", or "lc")?
carpentry: "dc"

# Overall title for pages.
title: "Reproducible reasearch using Jupyter Notebooks"

# Contact email address.
email: mateusz.kuzak@gmail.com

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "workshop"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: mkuza/2017-08-16-pyconpl

# Sites.
amy_site: "https://amy.software-carpentry.org/workshops"
lc_site: "https://librarycarpentry.github.io/"
dc_site: "http://datacarpentry.org"
swc_github: "https://github.com/swcarpentry"
swc_site: "https://software-carpentry.org"
swc_pages: "https://swcarpentry.github.io"
template_repo: "https://github.com/swcarpentry/styles"
example_repo: "https://github.com/swcarpentry/lesson-example"
example_site: "https://swcarpentry.github.com/lesson-example"
workshop_repo: "https://github.com/swcarpentry/workshop-template"
workshop_site: "https://swcarpentry.github.io/workshop-template"
training_site: "https://swcarpentry.github.io/instructor-training"
swc_installer: "https://github.com/swcarpentry/windows-installer/releases/download/v0.3/SWCarpentryInstaller.exe"

# Surveys.
dc_pre_assessment: "https://www.surveymonkey.com/r/dcpreworkshopassessment"
dc_post_assessment: "https://www.surveymonkey.com/r/dcpostworkshopassessment"

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am)
start_time: 0

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/
  extras:
    output: true

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: ..
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin

# Turn off built-in syntax highlighting.
highlighter: false
